---

- name: Teste env
  hosts: localhost
  gather_facts: no
    
  pre_tasks:
     
    - name: Carrega variaveis
      include_vars: "{{ item }}"
      loop: 
        - "{{ vars_file }}"

  tasks:
    - name: Debug
      debug:
        msg: "{{ ocp_credentials }}"
