---
- hosts: localhost
  gather_facts: yes

  tasks:
    - name: Install python deps
      ansible.builtin.pip:
        name:
          - netaddr

    - shell: pip list output
      register: outm

    - debug:
        msg: "{{ outm }}"

    - debug:
        msg: "{{ '10.4.244.0/24' | ansible.utils.ipaddr('size_usable') }}"
