---
- hosts: localhost
  gather_facts: yes

  tasks:
    - ansible.builtin.shell: pip install netaddr

    - shell: pip list output
      register: outm

    - debug:
        msg: "{{ outm }}"

    - debug:
        msg: "{{ '10.4.244.0/24' | ansible.utils.ipaddr('size_usable') }}"
